name: Automation Testing Pipeline

on:
  push:
    branches:
      - main

jobs:
  automation-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Chrome Installation
        run: |
          if ($env:RUNNER_OS -eq "Windows") { & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version }
          else { google-chrome --version }
        shell: pwsh

      - name: Grant Execute Permission to Gradle (For Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Project with Gradle
        run: .\gradlew.bat build

      - name: Run Automation Tests with TestNG
        run: .\gradlew.bat testng --info

      # Upload Test Reports as an Artifact
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: build/reports/tests/test  # Default location for HTML reports
