name: Automation Testing Pipeline

on:
  push:
    branches:
      - main

jobs:
  automation-tests:
    runs-on: ubuntu-latest  # Using Linux runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # ✅ Start Virtual Display (For GUI Tests)
      - name: Start Xvfb (Virtual Display)
        run: Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp -noreset -extension GLX -extension RANDR -extension RENDER &
        shell: bash

      - name: Set Display Environment Variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV  # Uses the virtual display

      - name: Build Project with Gradle
        run: ./gradlew build

      - name: Run Automation Tests with TestNG
        run: ./gradlew testng --info

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test
